//! `xtask` — developer tooling for the rustakka workspace.
//!
//! Subcommands:
//! * `sync-upstream` — diff against the tracked Akka.NET commit and print
//!   a checklist of files that changed upstream since last sync.
//! * `parity` — regenerate `docs/parity.md` from crate presence.

use std::env;
use std::process::Command;

use anyhow::{anyhow, Context, Result};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    let cmd = args.next().unwrap_or_else(|| "help".into());
    match cmd.as_str() {
        "sync-upstream" => sync_upstream(args.collect()),
        "parity" => parity(),
        "profile" => profile(args.collect()),
        "dashboard" => dashboard(args.collect()),
        "help" | "-h" | "--help" => {
            print_help();
            Ok(())
        }
        other => Err(anyhow!("unknown xtask subcommand: {other}")),
    }
}

fn print_help() {
    println!("rustakka xtask");
    println!();
    println!("USAGE:");
    println!("  cargo xtask <subcommand>");
    println!();
    println!("SUBCOMMANDS:");
    println!("  sync-upstream [--since <sha>]  diff akka.net since last synced commit");
    println!("  parity                          regenerate docs/parity.md");
    println!("  profile [extra args...]         run the actor perf profiler (rust only)");
    println!(
        "  dashboard [extra args...]       run rustakka-dashboard with embed-ui + common features"
    );
    println!("  help                            print this help");
}

fn dashboard(mut extra: Vec<String>) -> Result<()> {
    if extra.first().map(|s| s.as_str()) == Some("--") {
        extra.remove(0);
    }
    let features = std::env::var("RUSTAKKA_DASHBOARD_FEATURES")
        .unwrap_or_else(|_| "bin,embed-ui,aggregator,metrics-prometheus".into());
    let status = Command::new(env!("CARGO"))
        .args([
            "run",
            "-q",
            "-p",
            "rustakka-dashboard",
            "--features",
            &features,
            "--",
        ])
        .args(&extra)
        .status()
        .context("spawning cargo run for rustakka-dashboard")?;
    if !status.success() {
        return Err(anyhow!("rustakka-dashboard exited with {status}"));
    }
    Ok(())
}

fn sync_upstream(args: Vec<String>) -> Result<()> {
    // Delegate to scripts/sync-upstream.py. It handles the clone-if-missing,
    // fetch, diff-since, and markdown-formatting logic in one place so this
    // subcommand stays thin.
    let mut extra: Vec<String> = args;
    if extra.first().map(|s| s.as_str()) == Some("--") {
        extra.remove(0);
    }
    let python = which_python().context(
        "Python 3 is required to run scripts/sync-upstream.py. Install python3 or run \
         the script directly with your chosen interpreter.",
    )?;
    let script = std::path::Path::new("scripts").join("sync-upstream.py");
    if !script.exists() {
        return Err(anyhow!(
            "scripts/sync-upstream.py not found (cwd must be the workspace root)"
        ));
    }
    let status = Command::new(python)
        .arg(&script)
        .args(&extra)
        .status()
        .context("spawning python for scripts/sync-upstream.py")?;
    if !status.success() {
        return Err(anyhow!("sync-upstream.py exited with {status}"));
    }
    Ok(())
}

fn which_python() -> Result<String> {
    for candidate in ["python3", "python"] {
        if Command::new(candidate).arg("--version").output().is_ok() {
            return Ok(candidate.to_string());
        }
    }
    Err(anyhow!("no python3 / python found on PATH"))
}

fn profile(mut extra: Vec<String>) -> Result<()> {
    // The `cargo xtask` alias forwards a leading `--`; strip it so the
    // profiler binary doesn't see a bare separator.
    if extra.first().map(|s| s.as_str()) == Some("--") {
        extra.remove(0);
    }
    let status = Command::new(env!("CARGO"))
        .args(["run", "--release", "-q", "-p", "rustakka-profiler", "--"])
        .args(&extra)
        .status()
        .context("spawning cargo run for rustakka-profiler")?;
    if !status.success() {
        return Err(anyhow!("rustakka-profiler exited with {status}"));
    }
    Ok(())
}

fn parity() -> Result<()> {
    let crates_dir = std::path::Path::new("crates");
    let mut out = String::new();
    out.push_str("# Parity\n\n");
    out.push_str("Crate-by-crate presence report, regenerated by\n");
    out.push_str("`cargo xtask parity` from the workspace on disk.\n\n");

    // Rust crates: direct children of `crates/`, skipping the py-bindings group.
    out.push_str("## Rust crates\n\n");
    out.push_str("| Crate | Present |\n");
    out.push_str("|-------|---------|\n");
    let mut rust = 0usize;
    if crates_dir.is_dir() {
        let mut entries: Vec<_> = std::fs::read_dir(crates_dir)?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n != "py-bindings")
            .collect();
        entries.sort();
        for name in entries {
            out.push_str(&format!("| {name} | yes |\n"));
            rust += 1;
        }
    }

    // Python binding crates: children of `crates/py-bindings/`.
    let py_dir = crates_dir.join("py-bindings");
    out.push_str("\n## Python binding crates\n\n");
    out.push_str("| Crate | Python module | Present |\n");
    out.push_str("|-------|---------------|---------|\n");
    let mut py = 0usize;
    if py_dir.is_dir() {
        let mut entries: Vec<_> = std::fs::read_dir(&py_dir)?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        entries.sort();
        for name in entries {
            let py_mod = match name.as_str() {
                "pycore" => "rustakka (aggregate)".to_string(),
                other => format!("rustakka.{}", other.trim_start_matches("py").replace('-', "_")),
            };
            out.push_str(&format!("| {name} | {py_mod} | yes |\n"));
            py += 1;
        }
    }

    std::fs::create_dir_all("docs")?;
    std::fs::write("docs/parity.md", out)?;
    println!("wrote docs/parity.md ({rust} rust crates, {py} python binding crates)");
    Ok(())
}
